spring.application.name=donacion-microservice
server.port=8081

# Configuración de Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/donaton_db?createDatabaseIfNotExist=true
spring.datasource.username=
spring.datasource.password=

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true