spring.application.name=donaton-backend-usuarios
server.port=8083

# Configuración de Persistencia Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/donaton_usuarios_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true